-- MySQL Script generated by MySQL Workbench
-- 04/18/16 14:55:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `UCA` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) BINARY NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `lname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UCA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instructor` (
  `UCA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UCA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`course` (
  `CID` VARCHAR(15) NOT NULL,
  `semester` VARCHAR(45) NOT NULL,
  `courseName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CID`, `semester`, `courseName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`taughtCourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`taughtCourse` (
  `UCA` VARCHAR(45) NOT NULL,
  `CID` VARCHAR(15) NOT NULL,
  `semester` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UCA`, `CID`, `semester`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stakeholder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stakeholder` (
  `UCA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UCA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projectManager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projectManager` (
  `UCA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UCA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dev`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dev` (
  `UCA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UCA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`group` (
  `GID` VARCHAR(15) NOT NULL,
  `stakeholders` VARCHAR(45) NOT NULL,
  `projectManagers` VARCHAR(45) NOT NULL,
  `devs` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`GID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`groupsInCourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`groupsInCourse` (
  `CID` VARCHAR(15) NOT NULL,
  `semester` VARCHAR(45) NOT NULL,
  `GID` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`CID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`assessments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`assessments` (
  `GID` VARCHAR(15) NOT NULL,
  `aName` VARCHAR(45) NOT NULL,
  `AID` INT NOT NULL,
  PRIMARY KEY (`GID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`assessmentQuestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`assessmentQuestion` (
  `aid` INT NOT NULL,
  `q1` INT NULL,
  `q2` INT NULL,
  `q3` INT NULL,
  `q4` INT NULL,
  `q5` INT NULL,
  `q6` INT NULL,
  `q7` INT NULL,
  `q8` INT NULL,
  `q9` INT NULL,
  `q10` INT NULL,
  `q11` INT NULL,
  `q12` INT NULL,
  `q13` INT NULL,
  `q14` INT NULL,
  `q15` INT NULL,
  `q16` INT NULL,
  `q17` INT NULL,
  `q18` INT NULL,
  `q19` INT NULL,
  `q20` INT NULL,
  PRIMARY KEY (`aid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questions` (
  `QID` INT NOT NULL,
  `questionText` MEDIUMTEXT NULL,
  PRIMARY KEY (`QID`),
  UNIQUE INDEX `QID_UNIQUE` (`QID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type` (
  `TID` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `size` INT NOT NULL,
  `arrayName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`questionType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`questionType` (
  `QID` INT NOT NULL,
  `TID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`QID`, `TID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`answers` (
  `AID` INT NOT NULL,
  `UCA` VARCHAR(45) NOT NULL,
  `GID` VARCHAR(45) NOT NULL,
  `assassmentName` VARCHAR(100) NOT NULL,
  `a1` MEDIUMTEXT NULL,
  `a2` MEDIUMTEXT NULL,
  `a3` MEDIUMTEXT NULL,
  `a4` MEDIUMTEXT NULL,
  `a5` MEDIUMTEXT NULL,
  `a6` MEDIUMTEXT NULL,
  `a7` MEDIUMTEXT NULL,
  `a8` MEDIUMTEXT NULL,
  `a9` MEDIUMTEXT NULL,
  `a10` MEDIUMTEXT NULL,
  `a12` VARCHAR(2000) NULL,
  `a14` MEDIUMTEXT NULL,
  `a16` VARCHAR(2000) NULL,
  `a18` VARCHAR(2000) NULL,
  `a11` MEDIUMTEXT NULL,
  `a13` MEDIUMTEXT NULL,
  `a15` MEDIUMTEXT NULL,
  `a17` MEDIUMTEXT NULL,
  `a19` MEDIUMTEXT NULL,
  `a20` MEDIUMTEXT NULL,
  PRIMARY KEY (`AID`, `UCA`, `GID`, `assassmentName`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
